### ISSUE TITLE
imgdiff E 07-05 00:50:36 402355 402355 imgdiff.cpp:1363] Failed to set bonus data

### ISSUE THREAD

**Issue by NavlysChen** [TheXPerienceProject/android_bootable_recovery#1]
Sir, I need help in building xpe. I cant find other issues that are similar to it neither in github nor [RomDevelopment](https://t.me/alaskalinuxuser_romdevelopment) in tg.
https://hastebin.com/wifovetode.yaml
my trees
https://github.com/NavlysChen/android_device_xiaomi_sirius/tree/xpe-15.0-wip
https://github.com/NavlysChen/android_device_xiaomi_sdm710-common/tree/xpe-15.0-wip
https://github.com/NavlysChen/android_kernel_xiaomi_sdm710/tree/xpe-15.0-wip
https://github.com/NavlysChen/proprietary_vendor_xiaomi

**Comment by Klozz** [comment]
Let me check the issue :) 
I will reply to you as soon as possible.

**Comment by Klozz** [comment]
Now is fixed https://github.com/TheXPerienceProject/android_build/commit/c6c2f37904cbbe0f850fdde069a23853085d073d
